# Generated by Django 5.1.3 on 2024-11-17 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=256)),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('files', models.JSONField()),
            ],
        ),
    ]
