# Generated by Django 5.1.3 on 2024-11-24 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investimate_app', '0002_case_status_alter_case_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='insights',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
